sudo: required
services:
 - docker

before_install:
 - docker build -t moan22/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true moan22/react-test npm test

after_success:
 - docker build -t moan22/multi-client ./client
 - docker build -t moan22/multi-nginx ./nginx
 - docker build -t moan22/multi-server ./server
 - docker build -t moan22/multi-worker ./worker

# Login to docker hub

 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to docker hub

 - docker push moan22/multi-client
 - docker push moan22/multi-nginx
 - docker push moan22/multi-server
 - docker push moan22/multi-worker
